const MongoClient = require('mongodb').MongoClient;
MongoClient.connect('mongodb://127.0.0.1:27017/QUIZ_GAME',(err,client)=>{
    if(err){
        return console.log('Unable to0 connect to Mongodb');
    }
    const db = client.db('QUIZ_GAME');
    console.log('connected to the MongoDb server');

    db.collection('english_QUESTIONS').insertMany([{
        question:'',
        options:['','','',''],
        answer:'' 
    },{
        question:'',
        options:['','','',''],
        answer:''  
    },{
        question:'',
        options:['','','',''],
        answer:'' 
    },{
        question:'',
        options:['','','',''],
        answer:''  
    },{
        question:'',
        options:['','','',''],
        answer:''  
    },{
        question:'',
        options:['','','',''],
        answer:''   
    },{
        question:'',
        options:['','','',''],
        answer:''  
    },{
        question:' ',
        options:['','','',''],
        answer:''  
    },{
        question:'',
        options:['','','',''],
        answer:''   
    },{
        question:'',
        options:['','','',''],
        answer:''   
    },{
        question:'',
        options:['','','',''],
        answer:''   
    },{
        question:'',
        options:['','','',''],
        answer:''   
    },{
        question:'',
        options:['',' ','',''],
        answer:''    
    },{
        question:'',
        options:['','','',''],
        answer:''    
    },{
        question:'',
        options:['','','',''],
        answer:''  
    },{
        question:'',
        options:['','','',''],
        answer:''  
    },{
        question:'',
        options:['','','',''],
        answer:'' 
    },{
        question:'',
        options:['','','',''],
        answer:'' 
    },{
        question:'',
        options:['','','',''],
        answer:'' 
    },{
        question:'',
        options:['','','',''],
        answer:'' 
    },{
        question:'',
        options:['','','',''],
        answer:'' 
    },{
        question:'',
        options:['','','',''],
        answer:'' 
    },{
        question:'',
        options:['','','',''],
        answer:'' 
    },{
        question:'',
        options:['','','',''],
        answer:'' 
    },{
        question:'',
        options:['','','',''],
        answer:''
    },{
        question:'',
        options:['','','',''],
        answer:''
    },{
        question:'',
        options:['','','',''],
        answer:''
    },{
        question:'',
        options:['','','',''],
        answer:''
    },{
        question:'',
        options:['','','',''],
        answer:''
    },{
        question:'',
        options:['','','',''],
        answer:''
    },{
        question:'',
        options:['','','',''],
        answer:''
    },{
        question:'',
        options:['','','',''],
        answer:''
    },{
        question:'',
        options:['','','',''],
        answer:''
    },{
        question:'',
        options:['','','',''],
        answer:''
    },{
        question:'',
        options:['','','',''],
        answer:''
    },{
        question:'',
        options:['','','',''],
        answer:''
    },{
        question:'',
        options:['','','',''],
        answer:''
    },{
        question:'',
        options:['','','',''],
        answer:''
    }]);
});